In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('/content/kidney_disease.csv')

In [3]:
df.head()

   id   age    bp     sg   al   su  ...   dm cad appet   pe  ane  classification
0   0  48.0  80.0  1.020  1.0  0.0  ...  yes  no  good   no   no             ckd
1   1   7.0  50.0  1.020  4.0  0.0  ...   no  no  good   no   no             ckd
2   2  62.0  80.0  1.010  2.0  3.0  ...  yes  no  poor   no  yes             ckd
3   3  48.0  70.0  1.005  4.0  0.0  ...   no  no  poor  yes  yes             ckd
4   4  51.0  80.0  1.010  2.0  0.0  ...   no  no  good   no   no             ckd

[5 rows x 26 columns]

In [4]:
df.shape

(400, 26)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [6]:
df.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df = df.drop('id', axis=1)

In [9]:
df.describe()

              age          bp          sg  ...         sod         pot        hemo
count  391.000000  388.000000  353.000000  ...  313.000000  312.000000  348.000000
mean    51.483376   76.469072    1.017408  ...  137.528754    4.627244   12.526437
std     17.169714   13.683637    0.005717  ...   10.408752    3.193904    2.912587
min      2.000000   50.000000    1.005000  ...    4.500000    2.500000    3.100000
25%     42.000000   70.000000    1.010000  ...  135.000000    3.800000   10.300000
50%     55.000000   80.000000    1.020000  ...  138.000000    4.400000   12.650000
75%     64.500000   80.000000    1.020000  ...  142.000000    4.900000   15.000000
max     90.000000  180.000000    1.025000  ...  163.000000   47.000000   17.800000

[8 rows x 11 columns]

In [10]:
#handle categorical into numeric

df = df.applymap(lambda x: str(x).strip().lower() if isinstance(x, str) else x)

binary_cols = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification']

replace_dict = {
    'yes': 1, 'no': 0,
    'present': 1, 'notpresent': 0,
    'normal': 1, 'abnormal': 0,
    'good': 1, 'poor': 0,
    'ckd': 1, 'notckd': 0
}

df[binary_cols] = df[binary_cols].replace(replace_dict)

/tmp/ipython-input-262502075.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: str(x).strip().lower() if isinstance(x, str) else x)
/tmp/ipython-input-262502075.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[binary_cols] = df[binary_cols].replace(replace_dict)

In [11]:
df.head()

    age    bp     sg   al   su  rbc  ...   dm  cad  appet   pe  ane  classification
0  48.0  80.0  1.020  1.0  0.0  NaN  ...  1.0  0.0    1.0  0.0  0.0               1
1   7.0  50.0  1.020  4.0  0.0  NaN  ...  0.0  0.0    1.0  0.0  0.0               1
2  62.0  80.0  1.010  2.0  3.0  1.0  ...  1.0  0.0    0.0  0.0  1.0               1
3  48.0  70.0  1.005  4.0  0.0  1.0  ...  0.0  0.0    0.0  1.0  1.0               1
4  51.0  80.0  1.010  2.0  0.0  1.0  ...  0.0  0.0    1.0  0.0  0.0               1

[5 rows x 25 columns]

In [12]:
for col in ['pcv', 'wc', 'rc']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [13]:
df.head()

    age    bp     sg   al   su  rbc  ...   dm  cad  appet   pe  ane  classification
0  48.0  80.0  1.020  1.0  0.0  NaN  ...  1.0  0.0    1.0  0.0  0.0               1
1   7.0  50.0  1.020  4.0  0.0  NaN  ...  0.0  0.0    1.0  0.0  0.0               1
2  62.0  80.0  1.010  2.0  3.0  1.0  ...  1.0  0.0    0.0  0.0  1.0               1
3  48.0  70.0  1.005  4.0  0.0  1.0  ...  0.0  0.0    0.0  1.0  1.0               1
4  51.0  80.0  1.010  2.0  0.0  1.0  ...  0.0  0.0    1.0  0.0  0.0               1

[5 rows x 25 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             248 non-null    float64
 6   pc              335 non-null    float64
 7   pcc             396 non-null    float64
 8   ba              396 non-null    float64
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             329 non-null    float64
 16  wc              294 non-null    float64
 17  rc              269 non-null    float64
 18  htn             398 non-null    float64
 19  dm              398 non-null    float64
 20  cad             398 non-null    float64
 21  appet           399 non-null    float64
 22  pe              399 non-null    float64
 23  ane             399 non-null    float64
 24  classification  400 non-null    int64
dtypes: float64(24), int64(1)
memory usage: 78.3 KB

In [16]:
#handle missing value
# Fill numerical columns
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Fill categorical columns (0/1 type)
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [17]:
df.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [18]:
from sklearn.preprocessing import StandardScaler

In [20]:
X = df.drop('classification', axis=1)
y = df['classification']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        28
           1       1.00      1.00      1.00        52

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80